### ISSUE TITLE
How are contacts matched during 2 way sync?

### ISSUE THREAD

**Issue by shawnholt** [sciencegalleryderek/com.sciencegallery.mailchimp#1]
Wonderful contribution.  Are you using dedup logic in civicrm for any matching?  Do id's get stored to maintain matching and if so, what would happen if they get merged?

**Comment by sciencegalleryderek** [comment]
At the moment it's just using the email address as a key for the matching as we'd hope that email addresses are unique in a well maintained CRM! If there appears to be problems with this in the long term - we can look at storing the MailChimp unique contact ids somewhere in CiviCRM

**Comment by shawnholt** [comment]
"email addresses are unique in a well maintained CRM!"
well - you would hope :)  actually the issue is more about changing the email when deduping - but I'm sure this will be fine.  Dedupe has been a bit of a pain for a couple of clients.

In a future phase we might consider creating a table map of contact id's and mailchimp id's (may also save CPU on string-match lookups) with the modification timestamp so we only do the string compare if there is possible change.  I realize that is probably a much future phase though ....

Finally - I assume you are checking all email addresses, not just primary.

Wonderful contribution - are you using it in production?

**Comment by sciencegalleryderek** [comment]
We're only use the primary email for pushing to mailchimp, but check all email addresses coming back, if that makes sense,

Yes we're in production for the last month with it!

**Comment by shawnholt** [comment]
Great!  I'm going to start some full testing next week on drupal (pls let me know if I should use any patches).

  Yes, i think that does make sense.  So for outbound emails, we use primary but any bounce info or contact changes we update the civicrm contact(s) associated with any matching email. 

 So if I understand correctly:

if there is a duplicate civi contact (First, Last name) with 2 different primary emails and 1 matches mailchimp, we add 1 mailchimp contacts and send 2 emails. 

 If we have 1 civi contact with 2 emails, only primary is used to send / sync

.  If we have 2 duplicate (same First, Last) in mailchimp with 2 different emails that all match 2 emails for the same contact in civicrm, they are synced to that contact and no new civi records created.

**Comment by sciencegalleryderek** [comment]
As far as I understand it, in your first case, there'll only be one mailchimp contact created so there will only be one email sent by mailchimp, your other cases appear to be correct!
