### ISSUE TITLE
The contacts is deleted after i have add to mailing group sync to mailchimp

### ISSUE THREAD

**Issue by pgervaix** [sciencegalleryderek/com.sciencegallery.mailchimp#15]
Hi,
 have add manually 300 contacts in to the mailchimp group on the crm , the next day , contacts are disappears.
After search all the contacts it's on the Trash ?

Why ?

Thanks in advance

**Comment by sciencegalleryderek** [comment]
Probably due to the smartgroup sync issue #17 should be fixed in v1.3 branch
