### ISSUE TITLE
Chosen Parameters on Mailchimp Webhook

### ISSUE THREAD

**Issue by pgervaix** [sciencegalleryderek/com.sciencegallery.mailchimp#16]
hi,
Which parameters it's rights to set on in Mailchimp Webhook parameters? 

![screenshot003](https://f.cloud.github.com/assets/5338956/1397937/91d0e51c-3c93-11e3-8b77-cf30d8f89ed2.gif)

**Comment by sciencegalleryderek** [comment]
This should be set automatically by the settings script, the "subscribes" should be unchecked
