### ISSUE TITLE
Sync to groups in one list instead of multiple lists?

### ISSUE THREAD

**Issue by magnolia61** [sciencegalleryderek/com.sciencegallery.mailchimp#2]
First of all: thanks a lot for giving your love and time to this much needed integration!
The way mailchimp counts users is that they count double when appearing in different lists. We have a lot of overlap in our groups.
Would it be possible to have this extension sync to different groups in one list instead of a different list for every group?

**Comment by sciencegalleryderek** [comment]
@magnolia61 technically it would be possible to sync up to a single list and then have the CiviCRM groups as option groups for the member, however it's not on my radar at the moment as it doesn't match my own organisation's use case.

If someone were to branch this project and implement in such a way that either method was possible, I'd gladly merge!

**Comment by shawnholt** [comment]
If I understand correctly, you want one MC list - can't you just create a smart group of the sub-groups and sync?
