### ISSUE TITLE
Thanks! And two issues...

### ISSUE THREAD

**Issue by ghost** [sciencegalleryderek/com.sciencegallery.mailchimp#3]
Firstly, thank you so much for this excellent extension! Just playing now, and it looks like this is going to save us a lot of time and effort.

Two quick things:

Firstly, there's some Drupal specific code in /CRM/Mailchimp/Form/Setting.php. I changed drupal_set_message to CRM_Core_Error::createError( and it worked in our WordPress setup. I'm guessing there's probably a more appropriate command, though.

Secondly, you might want to warn people to disable logging while installing the extension. It doesn't create the shadow log table automatically, and if that's not in place then it'll throw a missing DB error when you try to add the API key. I disabled logging then recreated it and all was fine.

**Comment by sciencegalleryderek** [comment]
do you know what would be involved in creating a shadow log table? It would probably make sense to fix that issue instead of just disabling logging?

I'll fix the drupal message today - thanks for the spot

**Comment by bhahumanists** [comment]
Haven't seen anything in the API about doing this, annoyingly. Logging is still in beta, though.
