### ISSUE TITLE
Webhook authentication

### ISSUE THREAD

**Issue by ghost** [sciencegalleryderek/com.sciencegallery.mailchimp#6]
Probably a stupid question - how are you handing authentication for the webhook? On our WP setup it throws unauthenticated users to the login page.

**Comment by sciencegalleryderek** [comment]
The webhook page has the "make online contribution" access permission which should be assigned to anonymous users so that way there shouldn't be any login requrements

**Comment by bhahumanists** [comment]
Ok got this working, but only with a bit of a hack - the WP setup is weird. I had to change the webhook URL, and add an extra permission in civicrm.php.

Here's what I _think_ is going on:

Civi in WP separates back-end viewers from front-end viewers. Back-end viewers live in the WP admin interface and always need to log in. Front-end viewers see their pages appear within the WP theme and display to the general public. But the two types use different URL structures.

Back-end URL structure: https://whatever.org/wp-admin/admin.php?page=CiviCRM&q=civicrm/mailchimp/webhook

Front-end URL structure: https://whatever.org/?page=CiviCRM&q=civicrm/mailchimp/webhook

The MailChimp webhook needs the front-end link if it's to avoid authentication issues. But this address also needs to be added to the front-end whitelist, or it'll display a no permissions error. There's a whitelist of arguments for q= in civicrm.php. 

(if you're not on the whitelist then you don't even get as far as checking the 'make online contributions' or other permissions - it's literally a big list of arguments that are ok for the front-end)

 So, add this to the civicrm_check_permission() in civicrm.php:

```
// hack for MailChimp webhooks
if (
    $arg1 == 'mailchimp' && $arg2 == 'webhook'
) {
    return TRUE;
}
```

Sorry this isn't much use from a developer perspective - that's about my limit on WP/Civi integration. I don't know how you make this simple so the extension Just Works.

**Comment by awkale** [comment]
@awestbha where exactly did you put your code? And how? I found the following two spots:

``` php
    // check permission
      if (!civicrm_check_permission($args)) {
        if ($shortcode) {
          civicrm_set_frontendmessage();
        }
        else {
          add_filter('the_content', 'civicrm_set_frontendmessage');
        }
        return;
      }
```

and

``` php
    function civicrm_check_permission($args) {
      if ($args[0] != 'civicrm') {
        return FALSE;
      }
```

**Comment by bhahumanists** [comment]
Yep, under function civicrm_check_permission($args) - I put it straight after:

```
$arg2 = CRM_Utils_Array::value(2, $args);
$arg3 = CRM_Utils_Array::value(3, $args);
```

**Comment by awkale** [comment]
thanks @awestbha, It's syncing now.

Only I get this error when saving the settings page in Wordpress

```
The website encountered an error while retrieving https://brooklynsymphonyorchestra.org/wp-admin/admin.php?page=CiviCRM&q=civicrm/admin/setting/mailchimp. It may be down for maintenance or configured incorrectly.
Reload this webpage.
Press the reload button to resubmit the data needed to load the page.
Error code: 500
```

Maybe my URL is incorrect, I didn't quite understand the example URL `http:///civicrm/admin/setting/mailchimp` for a wordpress setup. That URL ending doesn't work unless I add `wp-admin/admin.php?page=CiviCRM&q=` before it

**Comment by bhahumanists** [comment]
@awkale You only need the front-end URL stuff for the webhook URL - everything else does indeed go through the normal wp-admin link.

I haven't got that error here - sounds like a php error.
