### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vishram74** [sciencegalleryderek/com.sciencegallery.mailchimp#7]
Hi
Thank you very much for this contribution.  I am testing it now with Drupal 7.  How long does it normally take for the lists to be reflected in Mailchimp after initial syncing?
I hope I have not done something wrong while installing.
I got a message that the sync was done successfully though
Can I view a log or something to confirm?

**Comment by sciencegalleryderek** [comment]
HI Vishram, there can be a considerable delay before the mailchimp UI reflects all the changes,

**Comment by vishram74** [comment]
Hi
Thanks for your reply. It has been almost a week. Could it take that long?
Someone mentioned that if you have logging enabled the extension may not
work. Is this a possible cause?
Thanks a lot
Vish

On Monday, 16 September 2013, sciencegalleryderek notifications@github.com
wrote:

> HI Vishram, there can be a considerable delay before the mailchimp UI
> reflects all the changes,
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Best Wishes
Dr Vish Ramakonar
CRM Consultant/Senior Business Analyst

## Sankhya Consultants

Web: www.crmconsulting.net.au

Tel: (08) 9259 0077****

Fax: (08) 6311 7480****

Mobile: 0404 713 249****

_Please Note:_ This message contains privileged and confidential
information intended only for the use of the addressee named above. If you
are not the intended recipient of this message, you must not disseminate
copy or take any action in reliance on it. If you have received this
message in error, please notify Sankhya immediately. Any views expressed in
this message are those of the individual sender, except where the sender
specifically states them to be the views of Sankhya. The sender cannot
guarantee that this email or any attachment to it is free of computer
viruses or other conditions which may damage or interfere with data,
hardware or software with which it might be used. It is sent on the strict
condition that the user carries out and relies on its own procedures for
ensuring that its use will not interfere with the recipients systems and
the recipient assumes all risk of use and absolves the sender of all
responsibility for any consequence of its use.

**Comment by sciencegalleryderek** [comment]
HI Vishram,

Are you still seeing this issue?

**Comment by vishram74** [comment]
Hi im able to sync contacts in civicrm and update mailchimp but not the
other way around.
If I update the list in mail chimp its not reflected in civicrm.
The webhook is not working.  Any idea why?
Also how do I configure the scheduled job for the smart group sync?

On Tuesday, 8 October 2013, sciencegalleryderek notifications@github.com
wrote:

> HI Vishram,
> 
> Are you still seeing this issue?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Best Wishes
Dr Vish Ramakonar
CRM Consultant/Senior Business Analyst

## Sankhya Consultants

Web: www.crmconsulting.net.au

Tel: (08) 9259 0077****

Fax: (08) 6311 7480****

Mobile: 0404 713 249****

_Please Note:_ This message contains privileged and confidential
information intended only for the use of the addressee named above. If you
are not the intended recipient of this message, you must not disseminate
copy or take any action in reliance on it. If you have received this
message in error, please notify Sankhya immediately. Any views expressed in
this message are those of the individual sender, except where the sender
specifically states them to be the views of Sankhya. The sender cannot
guarantee that this email or any attachment to it is free of computer
viruses or other conditions which may damage or interfere with data,
hardware or software with which it might be used. It is sent on the strict
condition that the user carries out and relies on its own procedures for
ensuring that its use will not interfere with the recipients systems and
the recipient assumes all risk of use and absolves the sender of all
responsibility for any consequence of its use.

**Comment by shawnholt** [comment]
I am going to run some tests this / next  week and will also see if I can reproduce.  Anything in the configuration I should look out for?  Is there a way to track the triggering?

I wonder if mailchimp dev team could help if necessary - they certainly stand to gain by this project :)
