### ISSUE TITLE
Can't seem to get smartgroupsync to work

### ISSUE THREAD

**Issue by magnolia61** [sciencegalleryderek/com.sciencegallery.mailchimp#8]
I cannot get the smartgroupsync period to work. Is there any documentation available? What I did was 
1) select the smartgroup in civicrm/admin/setting/mailchimp (with 41 contacts in it)
2) create a new list i MC with the same name 
3) run the scheduled job with default parameters...) 

Result is: Finished execution of Call Mailchimp.SyncSmartGroups API with result: Success (a:1:{i:0;i:1;})

But I don;t see any results in MC, even after waiting for a day or so :-| Suggestions?

**Comment by sciencegalleryderek** [comment]
Did you create the mailchimp list before or after you selected the group to sync in settings?
Are you using smart group cache?

**Comment by vishram74** [comment]
Can you please tell me what the parameters are to fill in in the scheduled job
Forgive my ignorance - cant seem to find the documentation for this.
Please see attachment
![mailchimp sync smart group parameters](https://f.cloud.github.com/assets/5449477/1157527/0e2eb0ca-1fa3-11e3-84e9-5c3baadfa883.JPG)
