### ISSUE TITLE
Groups and Smart Groups are not syncing

### ISSUE THREAD

**Issue by vishram74** [sciencegalleryderek/com.sciencegallery.mailchimp#9]
Hi

I just installed the extension at http://civicrm.org/extensions/mailchimp-sync/v10
I followed the instructions
1. Create lists on MailChimp with the same names as the groups you want to sync on CiviCRM
2. Install and enable the extenstion
3. Go to http://<yourdomain>/civicrm/admin/setting/mailchimp and enter your MailChimp API key and select your list
4. Run an initial sync at http://<yourdomain>/civicrm/admin/mailchimp/sync

When I went to enable to the extension I got an error saying something went wrong.  However when I checked in Civi under Administer and manage extensions, the extension was enabled and I was able to enter the mailchimp API, select the lists and run the sync as described in steps 3 -4.
However, 1 day later, there doesnt seem to be any contacts transferred from CiviCRM to Mailchimp.  Is there anything that I have missed ?

Btw I am using Drupal 7 and CiviCRM 4.2.6.
this is the error I got when I tried to enable the component (first attachment).
However after I got this error, when I went back to the manage extensions page, it said it was enabled (second attachment).
![mailchimp sync error](https://f.cloud.github.com/assets/5449477/1146810/fe133c7a-1e7f-11e3-9767-451926b0b22e.JPG)
![civi manage extensions page](https://f.cloud.github.com/assets/5449477/1146812/0343a43c-1e80-11e3-9d7b-f1a55f78399e.JPG)

**Comment by vishram74** [comment]
So far the contacts in CiviCRM are being created in Mailchimp.  If I remove a contact in Mailchimp it is not being reflected in Civi.  Is there something I have to set up with the webhooks?

Smartgroups not working as yet as im yet to set up the scheduled job - need some guidance on how to configure.

**Comment by shawnholt** [comment]
Is this still an issue?

**Comment by pgervaix** [comment]
I have the same error, the schedule job 

"Call Mailchimp.SyncSmartGroups API (Daily)
Call Mailchimp.SyncSmartGroups API
API Entity: Mailchimp
API Action: SyncSmartGroups"

delete all contacts on Mailchimp , any solutions??

**Comment by sciencegalleryderek** [comment]
See #17
